global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'
  group_by: [alertname, datacenter, app]

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#testing'
    text: 'https://internal.myorg.net/wiki/alerts/{{ .GroupLabels.app }}/{{ .GroupLabels.alertname }}'
